name: CI

on:
  - pull_request
  - push

env:
  CACHE_VERSION: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "24.0"
          rebar3-version: "3.18.0"

      - name: Cache Dialyzer PLT
        uses: actions/cache@v3
        with:
          path: _build/*/rebar3_*_plt
          key: dialyzer-plt-cache-${{ runner.os }}-v${{ env.CACHE_VERSION }}-${{ hashFiles('rebar.config') }}
          restore-keys: dialyzer-plt-cache-${{ runner.os }}-v${{ env.CACHE_VERSION }}-

      - name: Compile
        run: rebar3 compile

      - name: Test
        run: rebar3 eunit --cover --verbose

      - name: Dialyzer
        run: rebar3 dialyzer
